version: 2
registries:
  github-packages-npm:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{ secrets.GITHUB_TOKEN }}

updates:
  - package-ecosystem: npm
    directory: /
    open-pull-requests-limit: 10
    target-branch: main
    registries:
      - github-packages-npm
    schedule:
      interval: weekly
    groups:
      non-major:
        update-types:
          - 'minor'
          - 'patch'
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
